# Generated by Django 5.0 on 2023-12-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('Cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Field_name', models.CharField(max_length=50)),
                ('Field_description', models.TextField()),
                ('Crop_name', models.CharField(max_length=50)),
                ('Variety', models.CharField(max_length=20)),
                ('Planting_date', models.DateField()),
                ('Is_harvested', models.BooleanField(default=False)),
                ('Harvesting_date', models.DateField(blank=True, null=True)),
                ('Expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Expenses_description', models.TextField(blank=True)),
                ('Sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Sales_description', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Eid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Country_code', models.CharField(max_length=4)),
                ('Phone_number', models.CharField(max_length=9)),
                ('Position', models.CharField(max_length=10)),
                ('Salary', models.IntegerField()),
                ('Performance', models.CharField(max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('Tag_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Animal_type', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Breed', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Livestock',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('Number_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Equipment_name', models.CharField(max_length=20)),
                ('Purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Purchase_date', models.DateField()),
                ('Operation', models.TextField(blank=True)),
                ('Maintenance_activities', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Machinery',
            },
        ),
    ]
