# Generated by Django 5.0 on 2023-12-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Production_date', models.DateField()),
                ('Production_amount', models.CharField(max_length=20)),
                ('Feed_consumed', models.DecimalField(decimal_places=2, help_text='field consumed in kg', max_digits=10)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.livestock')),
            ],
        ),
    ]
