# Generated by Django 5.0 on 2023-12-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_livestock_production'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livestock_production',
            table='Livestock_production',
        ),
    ]
