# Generated by Django 5.0 on 2023-12-19 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_crops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('Number_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Equipment_name', models.CharField(max_length=20)),
                ('Purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Purchase_date', models.DateField()),
                ('Operation', models.TextField(blank=True)),
                ('Maintenance_activities', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Machinery',
            },
        ),
    ]
