# Generated by Django 5.0 on 2023-12-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_livestock_production_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock_production',
            name='Production_date',
            field=models.DateField(help_text='m/d/y'),
        ),
        migrations.CreateModel(
            name='Crop_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_date', models.DateField(help_text='m/d/y')),
                ('Expense_type', models.CharField(max_length=20)),
                ('Expense_description', models.TextField()),
                ('Budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Supplier', models.CharField(max_length=20)),
                ('Payment_method', models.CharField(max_length=10)),
                ('Receipt_number', models.CharField(max_length=20)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
            options={
                'db_table': 'Crop_expenses',
            },
        ),
    ]
