# Generated by Django 5.0 on 2023-12-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_machinery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('Tag_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Animal_type', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Breed', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Livestock',
            },
        ),
    ]
