# Generated by Django 5.0 on 2023-12-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_crops_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_date', models.DateField(help_text='m/d/y')),
                ('Quantity_sold', models.CharField(max_length=20)),
                ('Unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('Buyer_information', models.TextField()),
                ('Payment_method', models.CharField(max_length=20)),
                ('Payment_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], max_length=20)),
                ('Invoice_number', models.CharField(max_length=20)),
                ('Additional_notes', models.TextField(blank=True)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
        ),
    ]
