# Generated by Django 5.0 on 2023-12-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_crop_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='Sales',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='Sales_description',
        ),
    ]
