# Generated by Django 5.0 on 2023-12-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_crops_sales_remove_crops_sales_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_date', models.DateField(help_text='m/d/y')),
                ('Operation_name', models.CharField(max_length=20)),
                ('Additional_notes', models.TextField(blank=True)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
            options={
                'db_table': 'Crop_operations',
            },
        ),
    ]
