# Generated by Django 5.0 on 2023-12-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_machinery_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Machinery_part', models.CharField(max_length=100)),
                ('Technician_details', models.CharField(blank='True', max_length=100)),
                ('Cost', models.IntegerField()),
                ('Description', models.TextField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.machinery')),
            ],
            options={
                'db_table': 'Machinery_activities',
            },
        ),
    ]
