# Generated by Django 5.0 on 2024-01-01 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_machinery_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinery',
            name='Maintenance_activities',
        ),
        migrations.CreateModel(
            name='Milk_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('Livestock_number', models.IntegerField()),
                ('Morning_production', models.DecimalField(decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Midday_production', models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Evening_production', models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Morning_consumption', models.DecimalField(decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('Evening_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
