# Generated by Django 5.0 on 2024-01-05 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_milk_production_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_production',
            name='Month',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Year',
            field=models.IntegerField(blank=True, default=2024, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
